language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage

# command to run tests
script:
 - coverage run -m unittest discover --pattern *_test.py

after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email: 
    - koreal6803@gmail.com
